// Russian translations for field labels and descriptions.
// Used by ru.ts instead of the English defaults from constants.ts.

export const RU_FIELD_LABELS: Record<string, string> = {
  model: 'Модель по умолчанию',
  model_context_length: 'Окно контекста',
  fallback_providers: 'Резервные модели',
  toolsets: 'Включённые наборы инструментов',
  timezone: 'Часовой пояс',
  'display.personality': 'Личность',
  'display.show_reasoning': 'Блоки рассуждений',
  'desktop.repo_scan_enabled': 'Автопоиск репозиториев',
  'desktop.repo_scan_roots': 'Корни поиска репозиториев',
  'desktop.repo_scan_exclude_paths': 'Исключённые пути репозиториев',
  'agent.max_turns': 'Макс. шагов агента',
  'agent.image_input_mode': 'Вложения изображений',
  'agent.api_max_retries': 'Повторы запросов к API',
  'agent.service_tier': 'Уровень обслуживания',
  'agent.tool_use_enforcement': 'Контроль использования инструментов',
  'terminal.cwd': 'Рабочая директория',
  'terminal.backend': 'Бэкенд выполнения',
  'terminal.timeout': 'Тайм-аут команды',
  'terminal.persistent_shell': 'Постоянная оболочка',
  'terminal.env_passthrough': 'Передача переменных окружения',
  'terminal.docker_image': 'Образ Docker',
  'terminal.singularity_image': 'Образ Singularity',
  'terminal.modal_image': 'Образ Modal',
  'terminal.daytona_image': 'Образ Daytona',
  file_read_max_chars: 'Лимит чтения файла',
  'tool_output.max_bytes': 'Лимит вывода терминала',
  'tool_output.max_lines': 'Лимит страницы файла',
  'tool_output.max_line_length': 'Лимит длины строки',
  'code_execution.mode': 'Режим выполнения кода',
  'approvals.mode': 'Режим подтверждений',
  'approvals.timeout': 'Тайм-аут подтверждения',
  'approvals.mcp_reload_confirm': 'Подтверждать перезагрузку MCP',
  command_allowlist: 'Белый список команд',
  'security.redact_secrets': 'Скрывать секреты',
  'security.allow_private_urls': 'Разрешить приватные URL',
  'browser.allow_private_urls': 'Приватные URL в браузере',
  'browser.auto_local_for_private_urls': 'Локальный браузер для приватных URL',
  'checkpoints.enabled': 'Контрольные точки файлов',
  'checkpoints.max_snapshots': 'Макс. число контрольных точек',
  'voice.record_key': 'Горячая клавиша записи',
  'voice.max_recording_seconds': 'Макс. длительность записи',
  'voice.auto_tts': 'Читать ответы вслух',
  'stt.enabled': 'Распознавание речи',
  'stt.echo_transcripts': 'Показывать транскрипты',
  'stt.provider': 'Провайдер распознавания речи',
  'stt.local.model': 'Модель локального распознавания',
  'stt.local.language': 'Язык распознавания',
  'stt.openai.model': 'Модель OpenAI STT',
  'stt.groq.model': 'Модель Groq STT',
  'stt.mistral.model': 'Модель Mistral STT',
  'stt.elevenlabs.model_id': 'Модель ElevenLabs STT',
  'stt.elevenlabs.language_code': 'Язык ElevenLabs',
  'stt.elevenlabs.tag_audio_events': 'Размечать аудио-события',
  'stt.elevenlabs.diarize': 'Разделение говорящих',
  'tts.provider': 'Провайдер синтеза речи',
  'tts.edge.voice': 'Голос Edge',
  'tts.openai.model': 'Модель OpenAI TTS',
  'tts.openai.voice': 'Голос OpenAI',
  'tts.elevenlabs.voice_id': 'Голос ElevenLabs',
  'tts.elevenlabs.model_id': 'Модель ElevenLabs',
  'tts.xai.voice_id': 'Голос xAI (Grok)',
  'tts.xai.language': 'Язык xAI',
  'tts.xai.speed': 'Скорость воспроизведения xAI',
  'tts.xai.auto_speech_tags': 'Авто-теги речи xAI',
  'tts.xai.optimize_streaming_latency': 'Оптимизация задержки xAI',
  'tts.xai.sample_rate': 'Частота дискретизации xAI',
  'tts.xai.bit_rate': 'Битрейт xAI',
  'tts.minimax.model': 'Модель MiniMax TTS',
  'tts.minimax.voice_id': 'Голос MiniMax',
  'tts.mistral.model': 'Модель Mistral TTS',
  'tts.mistral.voice_id': 'Голос Mistral',
  'tts.gemini.model': 'Модель Gemini TTS',
  'tts.gemini.voice': 'Голос Gemini',
  'tts.neutts.model': 'Модель NeuTTS',
  'tts.neutts.device': 'Устройство NeuTTS',
  'tts.kittentts.model': 'Модель KittenTTS',
  'tts.kittentts.voice': 'Голос KittenTTS',
  'tts.piper.voice': 'Голос Piper',
  'tts.deepinfra.model': 'Модель DeepInfra TTS',
  'tts.deepinfra.voice': 'Голос DeepInfra',
  'memory.memory_enabled': 'Постоянная память',
  'memory.user_profile_enabled': 'Профиль пользователя',
  'memory.memory_char_limit': 'Лимит памяти',
  'memory.user_char_limit': 'Лимит профиля',
  'memory.provider': 'Провайдер памяти',
  'context.engine': 'Механизм контекста',
  'compression.enabled': 'Автосжатие',
  'compression.threshold': 'Порог сжатия',
  'compression.target_ratio': 'Целевое сжатие',
  'compression.protect_last_n': 'Защищённые последние сообщения',
  'delegation.model': 'Модель субагентов',
  'delegation.provider': 'Провайдер субагентов',
  'delegation.max_iterations': 'Лимит шагов субагента',
  'delegation.max_concurrent_children': 'Параллельные субагенты',
  'delegation.child_timeout_seconds': 'Тайм-аут субагента',
  'delegation.reasoning_effort': 'Усилия рассуждений субагента',
  'updates.non_interactive_local_changes': 'Локальные правки при обновлении'
}

export const RU_FIELD_DESCRIPTIONS: Record<string, string> = {
  model: 'Используется для новых чатов, если вы не выбрали другую модель в композере.',
  model_context_length: 'Максимальное количество токенов в окне контекста.',
  fallback_providers: 'Дополнительные провайдеры на случай отказа основного.',
  toolsets: 'Наборы инструментов, доступные агенту.',
  timezone: 'Часовой пояс для отображения времени.',
  'display.personality': 'Стиль ассистента по умолчанию для новых сессий.',
  'display.show_reasoning': 'Показывать блоки рассуждений, если их присылает бэкенд.',
  'desktop.repo_scan_enabled': 'Сканировать локальные папки на Git-репозитории для раздела «Проекты».',
  'desktop.repo_scan_roots': 'Папки для сканирования. Оставьте пустым — будет сканироваться домашняя директория.',
  'desktop.repo_scan_exclude_paths': 'Папки с их содержимым, которые нужно пропускать при поиске репозиториев.',
  'agent.max_turns': 'Максимальное количество итераций агента за один запрос.',
  'agent.image_input_mode': 'Как обрабатывать вложенные изображения.',
  'agent.api_max_retries': 'Сколько раз повторять запрос к API при сбое.',
  'agent.service_tier': 'Уровень обслуживания API (OpenAI/Anthropic).',
  'agent.tool_use_enforcement': 'Проверка согласованности вызовов инструментов.',
  'terminal.cwd': 'Папка проекта по умолчанию для работы инструментов и терминала.',
  'terminal.backend': 'Где выполнять команды: локально, Docker, SSH.',
  'terminal.timeout': 'Сколько секунд ждать завершения команды.',
  'terminal.persistent_shell': 'Сохранять состояние оболочки между командами.',
  'terminal.env_passthrough': 'Какие переменные окружения передавать в терминал.',
  'terminal.docker_image': 'Образ контейнера, используемый при бэкенде выполнения Docker.',
  'terminal.singularity_image': 'Образ, используемый при бэкенде выполнения Singularity.',
  'terminal.modal_image': 'Образ, используемый при бэкенде выполнения Modal.',
  'terminal.daytona_image': 'Образ, используемый при бэкенде выполнения Daytona.',
  file_read_max_chars: 'Максимум символов при чтении файла.',
  'tool_output.max_bytes': 'Максимальный размер вывода терминала в байтах.',
  'tool_output.max_lines': 'Максимум строк на страницу вывода.',
  'tool_output.max_line_length': 'Обрезать строки длиннее этого значения.',
  'code_execution.mode': 'Как выполнять код: безопасно, с подтверждением или без ограничений.',
  'approvals.mode': 'Когда запрашивать подтверждение перед выполнением.',
  'approvals.timeout': 'Сколько ждать ответа пользователя.',
  'approvals.mcp_reload_confirm': 'Спрашивать разрешение перед перезагрузкой MCP-серверов.',
  command_allowlist: 'Команды, которые можно выполнять без подтверждения.',
  'security.redact_secrets': 'Автоматически скрывать API-ключи и пароли в выводе.',
  'security.allow_private_urls': 'Разрешить доступ к localhost и внутренним адресам.',
  'browser.allow_private_urls': 'Разрешить браузеру открывать приватные URL.',
  'browser.auto_local_for_private_urls': 'Использовать локальный браузер для приватных URL.',
  'checkpoints.enabled': 'Создавать снимки для отката перед правкой файлов.',
  'checkpoints.max_snapshots': 'Сколько снимков отката хранить.',
  'voice.record_key': 'Горячая клавиша для запуска и остановки записи.',
  'voice.max_recording_seconds': 'Максимальная длительность одной записи в секундах.',
  'voice.auto_tts': 'Автоматически озвучивать ответы ассистента.',
  'stt.enabled': 'Включить локальное распознавание речи или через провайдера.',
  'stt.echo_transcripts': 'Дублировать сырую транскрипцию 🎙️ голосовых сообщений обратно в чат.',
  'stt.provider': 'Провайдер для распознавания речи.',
  'stt.local.model': 'Модель локального распознавания речи.',
  'stt.local.language': 'Язык распознавания речи.',
  'stt.openai.model': 'Модель OpenAI для распознавания речи.',
  'stt.groq.model': 'Модель Groq для распознавания речи (Whisper).',
  'stt.mistral.model': 'Модель Mistral для распознавания речи.',
  'stt.elevenlabs.model_id': 'Модель ElevenLabs для распознавания речи.',
  'stt.elevenlabs.language_code': 'Код языка ISO-639-3. Пусто — ElevenLabs определит язык сам.',
  'stt.elevenlabs.tag_audio_events': 'Размечать аудио-события в транскрипции.',
  'stt.elevenlabs.diarize': 'Разделять говорящих в расшифровке.',
  'tts.provider': 'Провайдер синтеза речи.',
  'tts.edge.voice': 'Голос Edge.',
  'tts.openai.model': 'Модель синтеза речи OpenAI.',
  'tts.openai.voice': 'Голос синтеза речи OpenAI.',
  'tts.elevenlabs.voice_id': 'Голос ElevenLabs.',
  'tts.elevenlabs.model_id': 'Модель синтеза ElevenLabs.',
  'tts.xai.voice_id': 'ID голоса xAI (например, eve) или свой голос.',
  'tts.xai.language': 'Код языка (например, en, pt-BR) или «auto» для автоопределения.',
  'tts.xai.speed': 'Скорость воспроизведения. 0.7 = медленнее, 1.0 = нормально, 1.5 = быстрее.',
  'tts.xai.auto_speech_tags': 'Пусть LLM вставляет выразительные теги ([laughing], [sighs]) в скрипт перед синтезом.',
  'tts.xai.optimize_streaming_latency': 'Компромисс задержки и качества. 0 = лучшее качество, 2 = минимальная задержка.',
  'tts.xai.sample_rate': 'Частота дискретизации в Гц. Выше = лучше качество, больше файл.',
  'tts.xai.bit_rate': 'Битрейт MP3 в бит/с. Применяется только при кодеке mp3.',
  'tts.minimax.model': 'Модель синтеза речи MiniMax.',
  'tts.minimax.voice_id': 'Голос MiniMax.',
  'tts.mistral.model': 'Модель синтеза речи Mistral.',
  'tts.mistral.voice_id': 'Голос Mistral.',
  'tts.gemini.model': 'Модель синтеза речи Gemini.',
  'tts.gemini.voice': 'Голос Gemini.',
  'tts.neutts.model': 'Модель NeuTTS.',
  'tts.neutts.device': 'Локальное устройство для инференса NeuTTS.',
  'tts.kittentts.model': 'Модель KittenTTS.',
  'tts.kittentts.voice': 'Голос KittenTTS.',
  'tts.piper.voice': 'Голос Piper.',
  'tts.deepinfra.model': 'Модель DeepInfra TTS.',
  'tts.deepinfra.voice': 'Голос DeepInfra.',
  'memory.memory_enabled': 'Сохранять постоянные воспоминания для будущих сессий.',
  'memory.user_profile_enabled': 'Вести компактный профиль предпочтений пользователя.',
  'memory.memory_char_limit': 'Максимальный размер постоянной памяти в символах.',
  'memory.user_char_limit': 'Максимальный размер профиля пользователя в символах.',
  'memory.provider': 'Провайдер постоянной памяти.',
  'context.engine': 'Стратегия управления длинными диалогами у предела контекста.',
  'compression.enabled': 'Сжимать старый контекст, когда диалог разрастается.',
  'compression.threshold': 'Порог заполнения контекста для запуска сжатия.',
  'compression.target_ratio': 'Целевая доля контекста после сжатия.',
  'compression.protect_last_n': 'Сколько последних сообщений не сжимать.',
  'delegation.model': 'Модель для делегированных субагентов.',
  'delegation.provider': 'Провайдер для делегированных субагентов.',
  'delegation.max_iterations': 'Максимальное число шагов субагента за один запуск.',
  'delegation.max_concurrent_children': 'Сколько субагентов может работать параллельно.',
  'delegation.child_timeout_seconds': 'Тайм-аут субагента. 0 = без ограничения.',
  'delegation.reasoning_effort': 'Уровень усилий рассуждений для делегированных субагентов.',
  'updates.non_interactive_local_changes':
    'Когда Hermes обновляется из приложения (без терминала): сохранить локальные правки кода (stash) или выбросить (discard). Обновления из терминала всегда спрашивают.'
}
